version: "3.8"
services:
  db:
    env_file:
      - .env
    container_name: "db_test"
    image: postgres:15.3-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge